name: Release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: keyval/otel-go-agent:${{ steps.vars.outputs.tag }}
        platforms: linux/amd64,linux/arm64
